### ISSUE TITLE
kernel security check failure bluescreen

### ISSUE THREAD

**Issue by ofaruka** [XaFF-XaFF/Cronos-Rootkit#10]
i am getting this blue screen whenever i load my driver.

**Comment by XaFF-XaFF** [comment]
What's your Windows version?

**Comment by ofaruka** [comment]
1809

**Comment by XaFF-XaFF** [comment]
@ofaruka Could you provide more information? How did you load driver? Did you disable DSE?

**Comment by ofaruka** [comment]
I have not disabled DSE. I used kdmapper to load it

**Comment by XaFF-XaFF** [comment]
> I have not disabled DSE. I used kdmapper to load it

Did you set custom entry point as required in kdmapper [readme?](https://github.com/TheCruZ/kdmapper#requirements)

**Comment by ofaruka** [comment]
Yes, I did. I can load my own driver with kdmapper but this gives me bluescreen

**Comment by XaFF-XaFF** [comment]
That's strange. I was able to load Cronos using kdmapper without any issues. I will do some tests and check if everything works properly.

**Comment by XaFF-XaFF** [comment]
@ofaruka You won't be able to load Cronos into kernel using kdmapper because the DriverObject is not passed into the driver entry point. This DriverObject is required to create object in Windows devices to communicate between user mode and kernel mode. The version of Cronos that I tested a while ago was modified in such a way that it did not require this object. That Cronos version will not be published, so I apologize for the confusion.
