### ISSUE TITLE
im getting BSOD after like 30 mins

### ISSUE THREAD

**Issue by relisek** [XaFF-XaFF/Cronos-Rootkit#14]

**Comment by XaFF-XaFF** [comment]
Hello, sorry for late response. BSOD is caused by PatchGuard. It is triggered by patching kernel memory for example with port hiding or process hiding. To get rid off the blue screens there are 2 ways: not using the features that are modifying kernel or to patch PatchGuard with a bootkit (https://github.com/Mattiwatti/EfiGuard)
